name: Create Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        spec: newJadeLauncherWINDOWS.spec

    - uses: actions/upload-artifact@v2
      with:
        name: Jade Launcher.exe
        path: dist
        
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '5 minutes' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        
  create-installer:
    runs-on: ubuntu-latest
  
    steps:
    - name: Create InnoSetup Installer
      uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
      with: 
        filepath: 'installerFile.iss'
        
    
